FROM opensuse/tumbleweed:latest


RUN zypper addrepo --repo http://download.opensuse.org/repositories/OBS:/Server:/Unstable/openSUSE_Factory/OBS:Server:Unstable.repo && \
    zypper -n --gpg-auto-import-keys refresh && \
    zypper -n dup && \
    zypper -n install \
        bsdtar \
        build \
        cpio \
        curl \
        file \
        findutils \
        git \
        git-lfs \
        go \
        iputils \
        jq \
        less \
        lsof \
        make \
        nano \
        npm \
        osc \
        podman \
        postgresql-server \
        python3-Django6 \
        python3-PyYAML \
        python3-behave \
        python3-cryptography\
        python3-pip \
        python3-poetry-core \
        python3-psycopg \
        python3-pytest \
        python3-setuptools \
        python3-urllib3 \
        python3-uv \
        ripgrep \
        ruff \
        sqlite3 \
        tar \
        tree \
        vim \
        wget \
        which

RUN pip3 install --break-system-packages django-bolt && \
    npm install -g @google/gemini-cli --ignore-scripts
